syntax = "proto3";

package workshop.v1;

import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";
import "sync/v1.proto";

option go_package = "workshop/v1;workshopv1";

message Rule {
  // Populated by the ListRules rpc. Leave blank when creating rules.
  string rule_id = 1;

  // The identifier for this rule, which will be interpreted differently depending on the rule_type.
  string identifier = 2;

  // The type of the rule, which determines how 'identifier' is interpreted.
  santa.sync.v1.RuleType rule_type = 3;

  // The policy for this rule, whether to allow or block.
  santa.sync.v1.Policy policy = 4;

  // If this rule triggers a block, this field can be used to display a customized message
  // to the user. Basic HTML is supported.
  string custom_msg = 5;

  // If this rule triggers a block, this field can be used to override the URL that the user
  // is taken to when clicking the "Open" button in the Santa UI. Placeholders are supported:
  // https://northpole.dev/deployment/configuration.html#eventdetailurl.
  string custom_url = 6;

  // The time that this rule was created. This field is ignored when creating rules.
  google.protobuf.Timestamp created_at = 7;

  // The time that this rule was last updated. This field is ignored when creating rules.
  google.protobuf.Timestamp updated_at = 8;

  // A free-form text field used to store extra information about this rule.
  string comment = 9;

  // Was this block rule created in response to malicious software? Default is
  // indicating that a block was by policy.
  enum BlockReason {
    BLOCK_REASON_UNSPECIFIED = 0;
    BLOCK_REASON_POLICY = 1;
    BLOCK_REASON_MALICIOUS = 2;
  }

  BlockReason block_reason = 10;

  message ScopeGlobal {
  }
  message ScopeGroup {
    string group_id = 1;
  }
  message ScopeHost {
    string host_id = 1;
  }

  // The scope of the rule. ScopeHost > ScopeGroup > ScopeGlobal.
  oneof scope {
    ScopeGlobal global = 11;
    // TODO: Rules with a group scope can be added to Workshop, but they are
    // not currently being applied. This is actively being worked on.
    ScopeGroup group = 12;
    ScopeHost host = 13;
  }
}

message Host {
  string uuid = 1;
  string hostname = 2;
  string os_version = 3;
  string santa_version = 4;
  santa.sync.v1.ClientMode client_mode = 5;
  google.protobuf.Timestamp last_sync = 6;
}

message Event {
  string uuid = 1;
  Host host = 2;

  string sha256 = 3;
  string cdhash = 4;
  string bundle_hash = 5;

  int32 pid = 6;
  int32 ppid = 7;
  string file_path = 8;
  string file_name = 9;
  string parent_name = 10;
  string executing_user = 11;
  google.protobuf.Timestamp execution_time = 12;
  repeated string logged_in_users = 13;
  santa.sync.v1.Decision decision = 14;
}

message BinaryBlockable {
  string sha256 = 1;
  string cdhash = 2;
  string signing_id = 3;
  string team_id = 4;
  string file_name = 5;

  CertificateBlockable signed_by = 6;

  repeated santa.sync.v1.Entitlement entitlements = 7;

  google.protobuf.Timestamp first_seen = 8;
}

message CertificateBlockable {
  string sha256 = 1;
  string common_name = 2;
  string organization = 3;
  string organizational_unit = 4;
  google.protobuf.Timestamp valid_from = 5;
  google.protobuf.Timestamp valid_until = 6;

  string signed_by = 7;

  google.protobuf.Timestamp first_seen = 8;
}

message BundleBlockable {
  string bundle_hash = 1;
  string bundle_id = 2;
  string bundle_name = 3;
  string bundle_version = 4;
  string bundle_short_version = 5;
  uint32 binary_count = 6;

  repeated BinaryBlockable binaries = 7;

  google.protobuf.Timestamp first_seen = 8;
}

enum BlockableKind {
  BLOCKABLE_KIND_UNSPECIFIED = 0;
  BLOCKABLE_KIND_BINARY = 1;
  BLOCKABLE_KIND_CERTIFICATE = 2;
  BLOCKABLE_KIND_BUNDLE = 3;
}

message SyncSettings {
  optional santa.sync.v1.ClientMode client_mode = 1;
  optional uint32 batch_size = 2;
  optional bool enable_bundles = 3;
  optional bool enable_transitive_rules = 4;
  optional bool enable_all_event_upload = 5;
  optional string allowed_path_regex = 6;
  optional string blocked_path_regex = 7;
  optional bool block_usb_mount = 8;
  repeated string remount_usb_mode = 9;
  optional bool clear_remount_usb_mode = 10;
}

message HTTPHeader {
    string key = 1;
    string value = 2;
}

// A RemoteRiskEnginePluginSettings is the configuration for Web hook based
// extension to the risk engine. Workshop will call out passing the event
// context to the server and the server will return a decision.
//
// This allows you to bridge the risk engine to any external service or threat
// intelligence database.
message RemoteRiskEnginePluginSettings {
    optional bool enabled = 1;                  // Is this plugin enabled or just configured?
    optional string name = 2;                   // Name you want the plugin to be identified by.
    optional string version = 3;                // Version of the plugin.
    optional string uuid = 4;                   // UUID of the plugin used for future updates
    optional string url = 5;                    // URL of the plugin server
    repeated HTTPHeader headers = 6;            // HTTP headers to be sent to the plugin server
    optional google.protobuf.Duration ttl = 7;  // How long to wait for a response from the plugin server is valid
}

// VirusTotalPluginSettings is the configuration for the VirusTotal plugin.
message VirusTotalPluginSettings {
    optional bool enabled = 1;                        // Is this plugin enabled or just configured?
    optional string api_key = 2;                      // The VirusTotal API key or URL to the API key in a secret store
    optional google.protobuf.Duration  cache_ttl = 3; // How long to cache answers from VirusTotal for (e.g. 30 minutes)
    optional uint32 num_cache_entries = 4;            // How many entries to cache (must be between 0 - 50,000)
    repeated string exclude_engines = 5;              // Which engines to exclude from the VirusTotal response
}

// ReversingLabsPluginSettings is the configuration for the ReversingLabs plugin.
message ReversingLabsPluginSettings {
    optional bool enabled = 1;                        // Is this plugin enabled or just configured?
    optional string username = 2;                     // The ReversingLabs username
    optional string password = 3;                     // The ReversingLabs password or URL to the password in a secret store
    optional google.protobuf.Duration cache_ttl = 4;  // How long to cache answers from ReversingLabs for (e.g. 30 minutes)
    optional uint32 num_cache_entries = 5;             // How many entries to cache (must be between 0 - 50,000)
}

// BlockableRule describes a policy to determine whether a blockable from a
// Santa Event can be approved. For example, you might not want to allow an
// application with certain entitlements to be approved by Workshop.
message BlockableRule {
    string rule = 1;                // The content of the CEL expression.
    string comment = 2;             // Free form comment to include in the rule.
}

// BlockableRulePluginSettings is the configuration for the built in
// BlockableRule plugin.
message BlockableRulePluginSettings {
    optional bool          enabled = 1; // Is this plugin enabled or just configured?
    repeated BlockableRule rules = 2;   // The rules for the risk engine.
}

// LocalPluginConfig is the default configuration for all embeded risk engine
// plugins for all embeded risk engine plugins
message LocalPluginSettings {
    optional VirusTotalPluginSettings virus_total = 1;
    optional ReversingLabsPluginSettings reversing_labs = 2;
    optional BlockableRulePluginSettings blockable_rules = 3;
}

// Risk Engine Settings
message RiskEngineSettings {
    optional bool enabled = 1;                                  // Is the risk engine enabled?
    optional google.protobuf.Duration plugin_timeout = 2;       // How long to wait for all plugins to respond
    optional LocalPluginSettings local_plugins = 3;             // Local plugin settings
    repeated RemoteRiskEnginePluginSettings remote_plugins = 4; // Remote plugin settings
}

// RiskEngineResult is the recorded result of a risk engine plugin evaluating a blockable.
message RiskEngineResult {
  enum Decision {
    DECISION_UNSPECIFIED = 0;
    DECISION_DENY = 1;
    DECISION_DENY_MALICIOUS = 2;
    DECISION_ALLOW = 3;
    DECISION_TIMEOUT = 4;
    DECISION_ERROR = 5;
  };

  google.protobuf.Timestamp timestamp = 1;
  string tx_id = 2;
  bool allowed = 3;
  Decision decision = 4;
  string plugin_name = 5;
  string plugin_uuid = 6;
  string explanation = 7;
  bool explanation_is_json = 8;
  optional string url = 9;
}
